### ISSUE TITLE
Save data locally

### ISSUE THREAD

**Issue by Yiwen-Zhang-259** [Yiwen-Zhang-259/ETC5543-cran-analysis#20]
Hi Emi,

As for some data reading from URL could being stuck and failed sometimes, I SAVE some of them as local .rda file and load again to use them once they successfully run. If this is ok ?  But I know reproducibility would be reduced through this way. 😢  I have pushed the code about this in "02-S03-release-date.Rmd" and "02-S05-github-commits.Rmd". Please have a look if convenient 😃

**Comment by emitanaka** [comment]
Yes that's okay
