### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by emitanaka** [Yiwen-Zhang-259/ETC5543-cran-analysis#21]
@Yiwen-Zhang-259 you need to change the wording of "What would affect the download counts". Remember that correlation doesn't imply causation. Some factors you mentioned have possible influence (e.g. number of times a package is updated), but some are _not_ causative factors (e.g. Github commit counts).

**Comment by Yiwen-Zhang-259** [comment]
@emitanaka Thanks for your nice reminding, Emi ! I have just changed this sentence to be "What may have correlation with download count?"  Could this be appropriate?

**Comment by emitanaka** [comment]
Maybe "What factors are linked to download counts?".

**Comment by Yiwen-Zhang-259** [comment]
@emitanaka  Thanks for recommendation, Emi ! this would be much appropriate !

**Comment by emitanaka** [comment]
I see that you have 29 slides. You might need to reduce this and focus on less points. You only have 10 minutes and make sure you don't go too fast over each slide. The slide by the way look fabulous!

**Comment by Yiwen-Zhang-259** [comment]
@emitanaka  Thanks Emi ! 😄  OK I am going to reduce my sides now

**Comment by Yiwen-Zhang-259** [comment]
@emitanaka , hi Emi, do you have some suggestions on which parts are no need to be included in my slides, Maybe I think the alphabetical order part can be excluded?   Or how many slides do you think I can contain in my pre 😃

**Comment by emitanaka** [comment]
Sorry only saw this now!
